# Saldae_Def1 <- htmltools::tags$p(
# "  The important thing about drawing a graph is that it gives you an immediate 'picture' of the data. This is important because it shows you straight away whether your data are grouped together, spread about, tending towards high or low values, or clustered around a central point. It will also show you whether you have any 'outliers', that is, very high or very low data values, which you may want to exclude from the analysis, or at least revisit to check that they are correct.",
#     style = htmltools::css(color='red','font-style' = 'italic')
# )
#
# Saldae_Def2 <- htmltools::tags$p(
#   "Forecasting is required in many situations. Stocking an inventory may require forecasts of demand months in advance. Telecommunication routing requires traffic forecasts a few minutes ahead. Whatever the circumstances or time horizons involved, forecasting is an important aid in effective and efficient planning",
#   style = htmltools::css(color='red','font-style' = 'italic')
# )
# Saldae_Def3 <- htmltools::tags$p(
# "Anomaly is rare and it represents an outlier, i.e., atypical case. The Concise Oxford Dictionaryof Mathematics Clapham (2013) denes an anomaly as an unusual and possibly erroneousobservation that does not follow the general pattern of a drawn population. Anomaly detectionis a branch of data mining that seeks to nd data points or patterns that do not t the overallpattern of the data. Studying anomalous behavior has been done in many applied areas such asnetwork security Peddabachigari u. a. (2007), nancial transactions Eskin u. a. (2002); Ahmedu. a. (2015), medical imaging Spence u. a. (2001), industrial damage detection Hollier und Austin(2002) and in earth science Das und Parthasarathy (2009), to name a few. As rare observationsoften carry important information, their proper detection is of great importance in practice.This thesis concentrates on anomaly detection in consumer micro-credit lending by usingthe state-of-the-art data mining methods.",
# style = htmltools::css(color='red','font-style' = 'italic')
# )
#
# Saldae_intro <- htmltools::tags$p(
#   "This is a template of interactive reporting output generated by [Saldae Analytics Platform](https://saldae-analytics.shinyapps.io/saldae-analytics-platform/).
# If you want to learn more about us and our service please visit our website:
#
#   [https://www.saldaeanalytics.com/](https://www.saldaeanalytics.com/)",
#   style = htmltools::css(color='black','font-style' = 'italic')
# )
#
# Sald_slickR <- slickR::slick_list(Saldae_intro,Saldae_Def1,Saldae_Def2,Saldae_Def3)
#
#
#
# slickR::slickR(Sald_slickR) + settings(dots = TRUE, adaptiveHeight = TRUE)
